---
# Dependencies install
- hosts: appServer
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install python3 default
      yum:
        name:
          - python-setuptools
          - python36
          - python36-pip
          - python36-devel
        state: present
    - name: Add repository
      yum_repository:
        name: IUS
        description: IUS YUM repo
        baseurl: https://centos7.iuscommunity.org/ius-release.rpm
    - name: Install python3 IUS
      yum:
        name:
          - python36u
          - python36u-libs
          - python36u-devel
          - python36u-pip

