---
# Dependencies install
- hosts: appServer
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install epel-release
      yum:
        name:
          - epel-release
        state: update
    - name: update
      yum:
        name:
          - "*" 
        state: present
    - name: Install Python3
      yum:
        name:
          - python36
        state: present
    - name: Install Python3
      yum:
        name:
          - python-setuptools
          - python36
          - python36-pip
          - python36-devel
        state: present
