---
# Dependencies install
- hosts: appServer
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install epel-release
      yum:
        name:
          - epel-release
        state: present
    - name: update
      yum:
        name:
          - "*"
        state: latest
    - name: Install python36
      yum:
        name:
          - python36
        state: present

