---
# Dependencies install
# Reference: https://www.rosehosting.com/blog/how-to-install-python-3-6-4-on-centos-7/
- hosts: appServer
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install epel
      yum:
        name: epel-release
        state: latest
    - name: Install python 3 from repo
      yum:
        name: python36
        state: present
    